/sensing/sen0592_radar:
  ros__parameters:
    baud: 115200
    slave_id: 1
    poll_period_s: 0.06
    response_deadline_s: 0.20
    inter_frame_sleep_s: 0.003
    min_range_m: 0.02
    max_range_m: 4.50
    field_of_view_rad: 0.26
    sensor_names: ["REAR", "LEFT2", "LEFT1", "RIGHT2", "RIGHT1", "FRONT"]
    frame_ids:
      - "radar_rear_link"
      - "radar_left2_link"
      - "radar_left1_link"
      - "radar_right2_link"
      - "radar_right1_link"
      - "radar_front_link"
    ports:
      - "/dev/ttyCH9344USB2"
      - "/dev/ttyCH9344USB3"
      - "/dev/ttyCH9344USB4"
      - "/dev/ttyCH9344USB5"
      - "/dev/ttyCH9344USB6"
      - "/dev/ttyCH9344USB7"
    topics:
      - "/sensing/radar/rear/range"
      - "/sensing/radar/left2/range"
      - "/sensing/radar/left1/range"
      - "/sensing/radar/right2/range"
      - "/sensing/radar/right1/range"
      - "/sensing/radar/front/range"
